// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("get_settings")),
	getTransfers: () => __TAURI_INVOKE<{ [key in string]: Transfer }>("get_transfers"),
	stopTransfer: (slot: string, discard: boolean) => typedError<null, AppError>(__TAURI_INVOKE("stop_transfer", { slot, discard })),
	getInstallPlan: () => typedError<InstallPlan, AppError>(__TAURI_INVOKE("get_install_plan")),
	saveSettings: (settings: AppSettings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
	getGameVersion: () => typedError<GameVersionResponse, AppError>(__TAURI_INVOKE("get_game_version")),
	getLauncherContent: () => typedError<LauncherContent, AppError>(__TAURI_INVOKE("get_launcher_content")),
	checkGameState: () => typedError<GameState, AppError>(__TAURI_INVOKE("check_game_state")),
	startDownload: () => typedError<null, AppError>(__TAURI_INVOKE("start_download")),
	cancelDownload: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_download")),
	/**
	 *  Discard a paused/cancelled download: stop it and delete the partial pack
	 *  files so they do not linger on disk. Used by the "Cancel" control (as
	 *  opposed to "Pause", which keeps the partial files for a later resume). Only
	 *  touches a launcher-managed `_download` cache, never a user-pointed folder.
	 */
	clearDownloadCache: () => typedError<null, AppError>(__TAURI_INVOKE("clear_download_cache")),
	verifyGameIntegrity: () => typedError<IntegrityComplete, AppError>(__TAURI_INVOKE("verify_game_integrity")),
	startUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("start_update")),
	/**
	 *  `with_mods` is the second launch action on the home screen: the game runs
	 *  on D3D11 with the 3DMigoto proxy loaded instead of the native Vulkan
	 *  renderer. Absent (tray menu, `--play`) means a normal launch.
	 */
	launchGame: (withMods: boolean | null) => typedError<null, AppError>(__TAURI_INVOKE("launch_game", { withMods })),
	/**
	 *  What the launcher can see of the mod setup: is the loader in place, how
	 *  many mods are installed, where to drop new ones.
	 */
	getModsStatus: () => typedError<ModsStatus, AppError>(__TAURI_INVOKE("get_mods_status")),
	/**
	 *  Download and install EFMI (and the 3DMigoto build it runs on) into the
	 *  game directory.
	 */
	installModLoader: () => typedError<LoaderInstallResult, AppError>(__TAURI_INVOKE("install_mod_loader")),
	/**  Remove the loader again. Installed mods are left alone. */
	uninstallModLoader: () => typedError<null, AppError>(__TAURI_INVOKE("uninstall_mod_loader")),
	/**
	 *  Open the `Mods` directory in the file manager, creating it on the way if
	 *  this is the user's first mod.
	 */
	openModsFolder: () => typedError<null, AppError>(__TAURI_INVOKE("open_mods_folder")),
	/**  OptiScaler in the game directory: installed or not, which release. */
	getOptiscalerStatus: () => typedError<OptiScalerStatus, AppError>(__TAURI_INVOKE("get_optiscaler_status")),
	/**
	 *  Download the latest OptiScaler release into the game directory, tuned
	 *  for this machine (Wine hooks, GPU spoofing without an NVIDIA driver).
	 */
	installOptiscaler: () => typedError<InstallResult, AppError>(__TAURI_INVOKE("install_optiscaler")),
	/**  Remove OptiScaler again, leaving everything else in the game directory. */
	uninstallOptiscaler: () => typedError<null, AppError>(__TAURI_INVOKE("uninstall_optiscaler")),
	stopGame: () => typedError<null, AppError>(__TAURI_INVOKE("stop_game")),
	isGameRunning: () => typedError<boolean, AppError>(__TAURI_INVOKE("is_game_running")),
	/**
	 *  Point the launcher at an already existing game installation (e.g. one made
	 *  by the official launcher under Bottles/Lutris). The folder must contain
	 *  Endfield.exe. The install is assumed to be up to date; if it is not, the
	 *  user can run Repair. Returns the version recorded.
	 */
	importExistingGame: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("import_existing_game", { path })),
	/**
	 *  Delete the game installation (game directory + its _download cache) and
	 *  reset the installed version. Refuses while the game is running, and only
	 *  acts when the directory actually contains the game.
	 */
	uninstallGame: () => typedError<null, AppError>(__TAURI_INVOKE("uninstall_game")),
	/**  Collect system / configuration info for bug reports. */
	getDebugInfo: () => typedError<string, AppError>(__TAURI_INVOKE("get_debug_info")),
	readLaunchLog: () => typedError<string, AppError>(__TAURI_INVOKE("read_launch_log")),
	repairGame: () => typedError<null, AppError>(__TAURI_INVOKE("repair_game")),
	updateInstalledVersion: (version: string) => typedError<null, AppError>(__TAURI_INVOKE("update_installed_version", { version })),
	checkSystemRequirements: () => typedError<SystemCheck, AppError>(__TAURI_INVOKE("check_system_requirements")),
	getDwprotonLatest: () => typedError<ProtonReleaseInfo, AppError>(__TAURI_INVOKE("get_dwproton_latest")),
	listDwprotonReleases: () => typedError<ProtonReleaseInfo[], AppError>(__TAURI_INVOKE("list_dwproton_releases")),
	/**
	 *  The DWProton tag we install by default and flag as recommended in the
	 *  picker; on macOS the Wine Staging version the Endfield module set was
	 *  last built and smoke-tested against.
	 */
	recommendedProtonTag: () => __TAURI_INVOKE<string>("recommended_proton_tag"),
	listInstalledProtons: () => typedError<InstalledProton_Serialize[], AppError>(__TAURI_INVOKE("list_installed_protons")),
	setActiveProton: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("set_active_proton", { path })),
	downloadDwproton: (release: {
	tag_name: string,
	download_url: string,
	file_name: string,
	size?: number | null,
	published_at?: string,
} | null) => typedError<null, AppError>(__TAURI_INVOKE("download_dwproton", { release })),
	cancelProtonDownload: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_proton_download")),
	/**  Full play-session journal (oldest first) for the stats card. */
	getGameSessions: () => typedError<GameSession[], AppError>(__TAURI_INVOKE("get_game_sessions")),
	getPrefixInfo: () => typedError<PrefixInfo, AppError>(__TAURI_INVOKE("get_prefix_info")),
	openPrefixFolder: () => typedError<null, AppError>(__TAURI_INVOKE("open_prefix_folder")),
	/**  Run a whitelisted Wine tool inside the game prefix (winecfg / regedit). */
	runPrefixTool: (tool: string) => typedError<null, AppError>(__TAURI_INVOKE("run_prefix_tool", { tool })),
	clearShaderCache: () => typedError<ShaderCacheResult, AppError>(__TAURI_INVOKE("clear_shader_cache")),
	backupPrefix: (dest: string) => typedError<null, AppError>(__TAURI_INVOKE("backup_prefix", { dest })),
	restorePrefix: (archive: string) => typedError<null, AppError>(__TAURI_INVOKE("restore_prefix", { archive })),
	resetPrefix: () => typedError<null, AppError>(__TAURI_INVOKE("reset_prefix")),
	/**
	 *  Switch the display off while a long download runs (Steam Deck on
	 *  battery, mostly). Returns as soon as the request is queued.
	 */
	turnOffScreen: () => typedError<null, AppError>(__TAURI_INVOKE("turn_off_screen")),
};

/* Types */
export type Announcement = {
	content?: string,
	jump_url?: string,
};

export type AppError = string;

export type AppSettings = {
	game_dir: string,
	download_dir: string,
	proton_dir: string,
	proton_prefix_dir?: string,
	language: string,
	installed_version: string,
	use_gamemode?: boolean,
	use_mangohud?: boolean,
	use_native_vulkan?: boolean,
	use_wayland?: boolean,
	use_dxvk_async?: boolean,
	on_launch_action?: string,
	disable_fsync?: boolean,
	disable_esync?: boolean,
	download_speed_limit?: number | null,
	download_max_concurrent?: number,
	/**
	 *  Keep the machine awake (no auto-suspend, no idle blanking) while a
	 *  transfer runs. On by default: a laptop that dozes off mid-download
	 *  resumes with a stalled connection, and nobody asks for that.
	 */
	inhibit_sleep_on_download?: boolean,
	use_canonical_hole?: boolean,
	/**
	 *  Route controllers through Proton's SDL input backend instead of its
	 *  hidraw one. On by default: outside Steam there is no Steam Input to
	 *  translate a raw HID pad into an XInput one, so hidraw leaves
	 *  XInput-only games with no controller at all (issue #32).
	 */
	use_sdl_input?: boolean,
	custom_env_vars?: string,
	custom_launch_args?: string,
	autostart_initialized?: boolean,
	use_prime_offload?: boolean,
	use_discord_rpc?: boolean,
	/**  Run the game inside the gamescope micro-compositor. */
	use_gamescope?: boolean,
	/**  gamescope window mode: "fullscreen" | "borderless" | "windowed". */
	gamescope_mode?: string,
	/**  Game render resolution as "WIDTHxHEIGHT", empty = native. */
	gamescope_render_res?: string,
	/**  gamescope output resolution as "WIDTHxHEIGHT", empty = auto. */
	gamescope_output_res?: string,
	/**  Nested refresh rate / FPS cap for gamescope, 0 = off. */
	gamescope_fps_limit?: number,
	/**  Upscaler: "auto" | "fsr" | "nis" | "integer" | "stretch". */
	gamescope_upscaler?: string,
	/**  Enable HDR output in gamescope (--hdr-enabled). */
	gamescope_hdr?: boolean,
	/**  Extra raw arguments appended to the gamescope invocation. */
	gamescope_extra_args?: string,
	/**
	 *  macOS only: where the Wine build that runs the game lives. Accepts the
	 *  `wine`/`wine64` binary itself, an install root holding `bin/wine`, or
	 *  a WineHQ-style `.app` bundle. Empty means the launcher's most recent
	 *  own install — see `game::launcher::macos::resolve_wine`.
	 */
	macos_wine_dir?: string,
	/**
	 *  macOS only: tell Rosetta to advertise AVX support to the translated
	 *  x86-64 code, which it hides unless asked; the game's binaries and
	 *  DXMT expect it. Harmless on an Intel Mac, which runs the game without
	 *  Rosetta at all.
	 */
	macos_advertise_avx?: boolean,
	/**
	 *  macOS only: Metal's built-in performance overlay (MTL_HUD_ENABLED),
	 *  the local equivalent of MangoHud.
	 */
	macos_metal_hud?: boolean,
	/**
	 *  macOS only: pass `-vulkan` and let the game drive its own Vulkan
	 *  renderer through winevulkan/MoltenVK, instead of `-force-d3d11` and
	 *  DXMT. Off by default: the game's Vulkan renderer does not draw a
	 *  frame over MoltenVK (a white screen, per Endfield_FineWine's report), and
	 *  DXMT is the path DXMT-equipped builds are tuned for. Kept as a switch
	 *  for the day MoltenVK catches up, and for telling a DXMT bug from a
	 *  game bug.
	 */
	macos_native_vulkan?: boolean,
	/**
	 *  Windows only: start the game elevated (UAC prompt) right away instead
	 *  of waiting for `CreateProcess` to fail with ERROR_ELEVATION_REQUIRED.
	 *  Some anti-cheat drivers need it; most installs do not.
	 */
	windows_run_as_admin?: boolean,
	/**
	 *  Windows only: pass `-vulkan` so the game drives its own Vulkan renderer
	 *  instead of Direct3D 11 — the path every Linux session runs on. The
	 *  official launcher never enables it on Windows, so it is off by default
	 *  and offered as an experiment. A modded launch ignores it: 3DMigoto
	 *  hooks D3D11 only.
	 */
	windows_use_vulkan?: boolean,
	/**
	 *  Windows only: register the game as "High performance" on the Graphics
	 *  settings page, so a hybrid-graphics laptop runs it on the dedicated
	 *  GPU. The Windows counterpart of `use_prime_offload`.
	 */
	windows_prefer_dgpu?: boolean,
	/**
	 *  Windows only: "Optimizations for windowed games" on the game's entry —
	 *  flip-model presentation for windowed and borderless modes (Windows 11
	 *  22H2 and later).
	 */
	windows_windowed_optimizations?: boolean,
	/**
	 *  Windows only: switch to the High performance power plan for the length
	 *  of a session and put the previous one back afterwards.
	 */
	windows_high_perf_power?: boolean,
	/**  Windows only: start the game in the above-normal priority class. */
	windows_high_priority?: boolean,
	/**
	 *  Run the game through the vkBasalt post-processing layer (sharpening,
	 *  colour correction, ReShade-format effects). Native Vulkan, so unlike
	 *  the 3DMigoto path it costs nothing extra in renderer terms.
	 */
	use_vkbasalt?: boolean,
	/**
	 *  Linux only: PROTON_DLSS_UPGRADE — swap the DLSS libraries the game
	 *  ships for the newer ones in the NVIDIA driver, the way the NVIDIA App's
	 *  "DLSS override" does on Windows. Gets the game the current DLSS 4
	 *  model without waiting for a patch. Needs an NVIDIA driver that
	 *  carries them (570 and later).
	 */
	dlss_upgrade?: boolean,
	/**
	 *  Linux only: PROTON_DLSS_INDICATOR — the driver's on-screen DLSS
	 *  status overlay, the one way to see the upscaler really is running.
	 */
	dlss_indicator?: boolean,
	/**
	 *  Linux only: DXVK_NVAPI_VKREFLEX — dxvk-nvapi's Vulkan Reflex layer, so
	 *  the game's Reflex setting works on the native Vulkan renderer too.
	 *  Ignored by Proton builds without the layer.
	 */
	use_vk_reflex?: boolean,
	/**
	 *  Show the "play with mods" action: the game then starts on its D3D11
	 *  path with the `d3d11.dll` proxy (3DMigoto/EFMI) loaded. Off by default —
	 *  it costs frames and the game is anti-cheat protected, so it is opt-in.
	 */
	mods_enabled?: boolean,
	/**  Accumulated in-game time in seconds. */
	total_playtime_secs?: number | null,
	/**  Unix timestamp (seconds) of the last game launch, 0 = never. */
	last_played?: number | null,
};

export type BackgroundImage = {
	url?: string,
	video_url?: string,
};

export type Banner = {
	url: string,
	jump_url?: string,
};

export type DiskRequirement = {
	path: string,
	available: number | null,
	required: number | null,
};

/**  One completed play session. */
export type GameSession = {
	/**  Unix timestamp (seconds) when the session started. */
	start: number | null,
	duration_secs: number | null,
};

export type GameState = { status: "not_installed"; latest_version: string } | { status: "update_available"; installed_version: string; latest_version: string } | { status: "ready"; version: string };

export type GameVersionResponse = {
	version: string,
	request_version?: string,
	action: number,
	pkg: PackageInfo,
	patch?: { [key in string]: string } | null,
};

export type InstallPlan = {
	download_bytes: number | null,
	unpacked_bytes: number | null,
	disks: DiskRequirement[],
	blocked: boolean,
};

export type InstallResult = {
	/**  Release tag that was installed. */
	version: string,
	/**  Number of files written into the game directory. */
	files: number | null,
};

export type InstalledProton = InstalledProton_Serialize | InstalledProton_Deserialize;

export type InstalledProton_Deserialize = {
	name: string,
	path: string,
	/**
	 *  macOS only: the DXMT version installed into this Wine, shown as a
	 *  badge in the picker. Absent on Linux, where the layer is Proton.
	 */
	dxmt: string | null,
	/**
	 *  macOS only: the Endfield module set (`wine-modules-<version>`) inside
	 *  this Wine — what gets the game past its anti-cheat. Absent on Linux.
	 */
	wine_patch: string | null,
};

export type InstalledProton_Serialize = {
	name: string,
	path: string,
	/**
	 *  macOS only: the DXMT version installed into this Wine, shown as a
	 *  badge in the picker. Absent on Linux, where the layer is Proton.
	 */
	dxmt?: string | null,
	/**
	 *  macOS only: the Endfield module set (`wine-modules-<version>`) inside
	 *  this Wine — what gets the game past its anti-cheat. Absent on Linux.
	 */
	wine_patch?: string | null,
};

export type IntegrityComplete = {
	checked: number | null,
	repaired: number | null,
	bytes_downloaded: number | null,
};

export type LauncherContent = {
	background?: BackgroundImage,
	banners?: Banner[],
	news_tabs?: NewsTab[],
	sidebars?: Sidebar[],
	single_ent?: SingleEnt | null,
};

export type LoaderInstallResult = {
	/**
	 *  EFMI release tag that was installed — the version a user comparing
	 *  notes with a mod author cares about.
	 */
	version: string,
	/**  Number of files written into the game directory. */
	files: number | null,
};

/**  What the launcher knows about the mod setup in the game directory. */
export type ModsStatus = {
	/**  A `d3d11.dll` proxy is present next to the game executable. */
	loader_installed: boolean,
	/**
	 *  `d3dx.ini` is there too — without it 3DMigoto loads but does nothing,
	 *  which is the usual "I installed it and no mods show up" case.
	 */
	loader_configured: boolean,
	/**
	 *  The installed loader is EFMI rather than the bare 3DMigoto build the
	 *  launcher used to install. The old one still loads, but it has been
	 *  unmaintained since January and mods built with the current toolkit
	 *  expect EFMI, so the UI offers an upgrade rather than staying quiet.
	 */
	efmi: boolean,
	/**  Absolute path of the `Mods` directory (whether or not it exists). */
	mods_dir: string,
	/**  Number of mods installed — every direct subdirectory counts as one. */
	mod_count: number | null,
	/**
	 *  ReShade (or another `dxgi.dll` proxy) is present. Detected rather than
	 *  installed: ReShade ships as an interactive setup, and its add-ons —
	 *  RenoDX and friends — are configured by hand anyway. All the launcher
	 *  owes it is the DLL override, which the modded launch sets regardless.
	 */
	reshade_installed: boolean,
	/**  The game directory itself is missing, so nothing else here means much. */
	game_dir_missing: boolean,
};

export type NewsTab = {
	tabName: string,
	announcements?: Announcement[],
};

/**  What the launcher knows about OptiScaler in the game directory. */
export type OptiScalerStatus = {
	/**  The proxy and its ini are both next to the game executable. */
	installed: boolean,
	/**  Release tag of the launcher's own install, empty for a hand-made one. */
	version: string,
	/**  The game directory itself is missing, so nothing else here means much. */
	game_dir_missing: boolean,
};

export type PackFile = {
	url: string,
	md5: string,
	package_size: string,
};

export type PackageInfo = {
	packs: PackFile[],
	total_size: string,
	game_files_md5?: string,
	file_path?: string,
};

export type PrefixInfo = {
	path: string,
	exists: boolean,
};

export type ProtonReleaseInfo = {
	tag_name: string,
	download_url: string,
	file_name: string,
	size?: number | null,
	published_at?: string,
};

export type ShaderCacheResult = {
	files_removed: number | null,
	bytes_freed: number | null,
};

export type Sidebar = {
	media?: string,
	jump_url?: string,
	icon_url?: string,
	sidebar_labels?: SidebarLabel[],
};

export type SidebarLabel = {
	content?: string,
	jump_url?: string,
};

export type SingleEnt = {
	version_url?: string,
	button_url?: string,
	button_hover_url?: string,
	jump_url?: string,
};

export type SystemCheck = {
	/**
	 *  `"linux"`, `"macos"` or `"windows"`. The frontend keys every
	 *  Proton/Wine-only section off this rather than guessing from the other
	 *  flags.
	 */
	platform: string,
	/**
	 *  A compatibility layer is ready: Proton on Linux, some Wine build on
	 *  macOS. Always true on Windows, where none is needed.
	 */
	has_proton: boolean,
	has_ntsync: boolean,
	has_gamemode: boolean,
	has_mangohud: boolean,
	has_gamescope: boolean,
	/**
	 *  The NVIDIA proprietary driver is loaded. What decides whether the
	 *  DLSS knobs mean anything and whether OptiScaler has to spoof a GPU.
	 */
	has_nvidia: boolean,
	/**
	 *  More than one GPU vendor in the box — a laptop with an iGPU and a
	 *  dedicated card, where the game may land on the wrong one unless PRIME
	 *  offload is on.
	 */
	hybrid_graphics: boolean,
	/**
	 *  The vkBasalt Vulkan layer is installed on the host. Unlike the
	 *  wrappers above it is not a command but a layer manifest, so it is
	 *  looked up by file rather than by `which`.
	 */
	has_vkbasalt: boolean,
	/**  The desktop exposes a "turn off screen" call the launcher can make. */
	can_turn_off_screen: boolean,
	proton_path: string,
	/**
	 *  macOS on Apple silicon: Rosetta 2 is installed, so the x86-64 Wine
	 *  (and the game) can run at all. True everywhere else — Intel Macs run
	 *  x86-64 natively and the other platforms have no such thing.
	 */
	has_rosetta: boolean,
	/**
	 *  macOS: the DXMT version inside the active Wine, empty if none. What
	 *  tells the UI whether D3D11 goes to Metal or to the OpenGL fallback.
	 */
	dxmt_version: string,
	/**
	 *  macOS: the Endfield module set inside the active Wine, empty if none —
	 *  in which case the anti-cheat will not load and the UI says so.
	 */
	wine_patch_version: string,
};

export type Transfer = {
	id: string,
	slot: string,
	kind: string,
	status: string,
	game_dir: string,
	download_dir: string,
	progress: { [key in string]: string },
	error: string | null,
	result: { [key in string]: string },
	discard?: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

